apiVersion: v1
kind: List
items:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: fruit-shop
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: fruit-shop
      template:
        metadata:
          labels:
            name: fruit-shop
        spec:
          securityContext:
            seccompProfile: 
              type: RuntimeDefault 
            runAsNonRoot: true
          containers:
            - name: fruit-shop
              image: quay.io/ecosystem-appeng/mongo-quickstart:0.0.2-SNAPSHOT
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
  - kind: Service
    apiVersion: v1
    metadata:
      name: fruit-shop
      labels:
        name: fruit-shop
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: fruit-shop
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: fruit-shop
      labels:
        name: fruit-shop
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: fruit-shop
